theme: minima
description: This is where I deliver the value and ideas
title: The Knowledge Pool
email: sunjiong821@gmail.com
#baseurl: ""
#url: ""
twitter_username: @SunJiong
github_username: @SunJiong
weibo_username: @Sunjiong
